export enum AlertType {
  SET_ALERT = 'SET_ALERT',
  REMOVE_ALERT = 'REMOVE_ALERT'
}

export enum AuthType {
  REGISTER_SUCCESS = 'REGISTER_SUCCESS',
  REGISTER_FAIL = 'REGISTER_FAIL',
  USER_LOADED = 'USER_LOADED',
  AUTH_ERROR = 'AUTH_ERROR',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAIL = 'LOGIN_FAIL',
  LOGOUT = 'LOGOUT',
  LOGOUT_FAIL = 'LOGOUT_FAIL'
}

export enum RecordingType {
  SEND_RECORDING = 'SEND_RECORDING',
  GET_RECORDING = 'GET_RECORDING',
  RECORDING_RESULT_FAIL = 'RECORDING_RESULT_FAIL',
  REMOVE_RECORDING = 'REMOVE_RECORDING'
}

export enum DevelopmentModeType {
  ENABLE_DEVELOPMENT_MODE = 'ENABLE_DEVELOPMENT_MODE',
  DISABLE_DEVELOPMENT_MODE = 'DISABLE_DEVELOPMENT_MODE'
}

export enum ProfileType {
  GET_PROFILE = 'GET_PROFILE',
  PROFILE_ERROR = 'PROFILE_ERROR'
}