export enum LoginAlertType {
  SET_LOGIN_ALERT = 'SET_LOGIN_ALERT',
  REMOVE_LOGIN_ALERT = 'REMOVE_LOGIN_ALERT'
}

export enum AuthType {
  REGISTER_SUCCESS = 'REGISTER_SUCCESS',
  REGISTER_FAIL = 'REGISTER_FAIL',
  USER_LOADED = 'USER_LOADED',
  AUTH_ERROR = 'AUTH_ERROR',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAIL = 'LOGIN_FAIL',
  LOGOUT = 'LOGOUT',
  LOGOUT_FAIL = 'LOGOUT_FAIL'
}

export enum RecordingType {
  SEND_RECORDING = 'SEND_RECORDING',
  RECORDING_RESULT_SUCCESS = 'RECORDING_RESULT_SUCCESS',
  RECORDING_RESULT_FAIL = 'RECORDING_RESULT_FAIL'
}

export enum DevelopmentModeType {
  ENABLE_DEVELOPMENT_MODE = 'ENABLE_DEVELOPMENT_MODE',
  DISABLE_DEVELOPMENT_MODE = 'DISABLE_DEVELOPMENT_MODE'
}
